[package]
name = "mdsrc2txt"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4.1", features = ["derive"] }
walkdir = "2.3"
zip = "0.6"

[dev-dependencies]
tempfile = "3.5"
